[package]
name = "cnLogger"
version = "0.1.0"
description = "A comprehensive logging system for Internet Computer canisters"
repository = "https://github.com/yourusername/cnLogger"
keywords = ["logging", "debug", "internet-computer", "dfinity", "motoko"]
license = "MIT"

[dependencies]
base = "0.10.0"